name: Build artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # build packages
  build_export_be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.m2
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('exporter/gradle.properties', 'exporter/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build export back-end native
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          cd exporter/
          echo " ====================== Building native be ====================== \n"
          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
          echo " ====================== Native be build completed ====================== \n"
          ls -lh

      - name: Uploading build
        uses: actions/upload-artifact@v3
        with:
          name: function-be.zip
          path: /home/runner/work/sync-app-functions/sync-app-functions/exporter/build/function.zip


#      - uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          DEST_DIR: "/export-be.zip"
#          SOURCE_DIR: '/home/runner/work/sync-app-functions/sync-app-functions/exporter/build/function.zip'
#          SOURCE_DIR: 'exporter/build/function.zip'
#          SOURCE_DIR: '/home/runner/work/sync-app-functions/sync-app-functions/exporter/build/function.zip'


#
#  build_export_api:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: graalvm/setup-graalvm@v1
#        with:
#          version: 'latest'
#          java-version: '17'
#          components: 'native-image'
#
#      - name: Cache build files
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.m2
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('exporter-api/gradle.properties', 'exporter-api/build.gradle') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle
#
#      - name: Build export back-end native
#        run: |
#          echo "GRAALVM_HOME: $GRAALVM_HOME"
#          echo "JAVA_HOME: $JAVA_HOME"
#          java --version
#          gu --version
#          native-image --version
#          cd exporter-api/
#          echo " ====================== Building native api ====================== \n"
#          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
#          echo " ====================== Native api build completed ====================== \n"
