name: Build artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # build packages
  build_export_be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.m2
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('exporter/gradle.properties', 'exporter/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build export back-end native
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          cd exporter/
          echo " ====================== Building native be ====================== \n"
          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
          echo " ====================== Native be build completed ====================== \n"
          ls -lh
          mv /home/runner/work/sync-app-functions/sync-app-functions/exporter/build/function.zip /home/runner/work/sync-app-functions/sync-app-functions/export-be.zip
          ls -lh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "export-be.zip"
          artifactContentType: "application/zip"
          allowUpdates: true
          makeLatest: true
          name: build-${{github.run_number}}
          tag: build-${{github.run_number}}

#  build_export_api:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: graalvm/setup-graalvm@v1
#        with:
#          version: 'latest'
#          java-version: '17'
#          components: 'native-image'
#
#      - name: Cache build files
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.m2
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('exporter-api/gradle.properties', 'exporter-api/build.gradle') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle
#
#      - name: Build export back-end native
#        run: |
#          echo "GRAALVM_HOME: $GRAALVM_HOME"
#          echo "JAVA_HOME: $JAVA_HOME"
#          java --version
#          gu --version
#          native-image --version
#          cd exporter-api/
#          echo " ====================== Building native api ====================== \n"
#          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
#          echo " ====================== Native api build completed ====================== \n"
